// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHe3kgpWmXBjITo4S47Tyz8hMv0JJbj88',
    appId: '1:1005389576515:web:63fc8f7ded5e26684fd7f6',
    messagingSenderId: '1005389576515',
    projectId: 'favspot',
    authDomain: 'favspot.firebaseapp.com',
    databaseURL: 'https://favspot-default-rtdb.firebaseio.com',
    storageBucket: 'favspot.appspot.com',
    measurementId: 'G-4L3TSPR8SB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGEmxBHO13IaoZsl1F9EIw5AH7OilT5Bo',
    appId: '1:1005389576515:android:856a01f130c0c74e4fd7f6',
    messagingSenderId: '1005389576515',
    projectId: 'favspot',
    databaseURL: 'https://favspot-default-rtdb.firebaseio.com',
    storageBucket: 'favspot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDSmfAwgi0-Ujh0klH1f2KeW1GbsZNuwI',
    appId: '1:1005389576515:ios:9de9dca9eef0d0054fd7f6',
    messagingSenderId: '1005389576515',
    projectId: 'favspot',
    databaseURL: 'https://favspot-default-rtdb.firebaseio.com',
    storageBucket: 'favspot.appspot.com',
    androidClientId: '1005389576515-qhjjhlsje2j1hsu72eq7uk8f296livgu.apps.googleusercontent.com',
    iosClientId: '1005389576515-48jncupqkmvjtoa534s0r7o2sajhndgj.apps.googleusercontent.com',
    iosBundleId: 'dev.smartx.favspot',
  );
}
